---
fullnameOverride: external-dns-dnscaster

logLevel: debug
logFormat: text

interval: 5s
sources:
  - gateway-httproute
  - ingress
  - service
  - crd
registry: txt
txtOwnerId: external-dns
domainFilters: ["dnstest.pinax.network"]
excludeDomains: []
policy: sync

provider:
  name: webhook
  webhook:
    image:
      repository: localhost:5001/external-dns-dnscaster
      tag: latest
      pullPolicy: Always
    env:
      - name: LOG_FORMAT
        value: text
      - name: LOG_LEVEL
        value: debug
      - name: DOMAIN_FILTER
        value: "dnstest.pinax.network"

      - name: DNSCASTER_NAMESERVER_SET_ID
        value: nst_0wd1fQSt2uYYNP4j3YLCZX
      - name: DNSCASTER_API_KEY
        valueFrom:
          secretKeyRef:
            name: dnscaster-api-key
            key: API_KEY
