---
apiVersion: v1
kind: Service
metadata:
  name: nginx-external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "service.dnstest.pinax.network"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
